// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3EfCoreWizardDemo.Models;

public partial class LkpDepartment
{
    [Key]
    public int departmentId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public bool IsDelete { get; set; }

    [Required]
    [StringLength(50)]
    public string ManagerName { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<LkpEmployee> LkpEmployees { get; set; } = new List<LkpEmployee>();
}