// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3EfCoreWizardDemo.Models;

public partial class LkpEmployee
{
    [Key]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Jobtitle { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Salary { get; set; }

    [StringLength(250)]
    public string Photo { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string Mobile { get; set; }

    public int? DepartmentId { get; set; }

    public bool IsDelete { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("LkpEmployees")]
    public virtual LkpDepartment Department { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<SupplyOrder> SupplyOrders { get; set; } = new List<SupplyOrder>();
}