// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3EfCoreWizardDemo.Models;

public partial class OrderDetail
{
    [Key]
    public int OrderDetails { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int Quatity { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderDetails")]
    public virtual Product Product { get; set; }
}