// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3EfCoreWizardDemo.Models;

public partial class Vendor
{
    [Key]
    public int VendorId { get; set; }

    [Required]
    [StringLength(50)]
    public string VendorName { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal TotalBalance { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Creadit { get; set; }

    public bool? IsDelete { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<SupplyOrder> SupplyOrders { get; set; } = new List<SupplyOrder>();
}